require('plugins')
require('settings')
require('plug-config/barbar')
require('plug-config/autopairs')
require('plug-config/floaterm')
require('plug-config/treesitter')
require('plug-config/colorizer')
require('plug-config/telescope')
require('plug-config/galaxyline')
require('colorscheme')
require('keymappings')
vim.cmd('source ~/.config/nvim/vimscript/startify.vim')
