require('plugins')
require('settings')
require('colorscheme')
require('keymappings')

-- Plugins Config
-- require('plug-config/bufferline')
require('plug-config/barbar')
require('plug-config/autopairs')
require('plug-config/floaterm')
require('plug-config/treesitter')
require('plug-config/colorizer')
require('plug-config/telescope')
require('plug-config/galaxyline')
require('plug-config/gitsigns')
require('plug-config/compe')
require('plug-config/vim-rooter')
require('plug-config/lspinstall')
require('plug-config/lspsaga')
require('plug-config/lsp-trouble')
require('plug-config/lsp')
--require('plug-config/dashboard')
vim.cmd('source ~/.config/nvim/vimscript/startify.vim')
